### ISSUE TITLE
External mic isn't working

### ISSUE THREAD

**Issue by caiopm** [leocg/Hackintosh-Dell-G5-5590#11]
Hey, using this AppleALC layout, the external mic doesn't work. I will to try to create a new custom layout for our laptop. 
The power cord problem maybe I know how to fix, patching the ACPI files. I have fixed that using Clover + patched DSDT in the past, but I will try to create a custom SSDT to inject with OpenCore. BTW, are you brazilian? Do you have whatsapp? If so, we can talk faster on it.

**Comment by leocg** [comment]
Sim, BR aqui! Prefiro usar o discord porque fica mais fácil para trocar arquivos: SegrobOel#0801

**Comment by giorgimoreira** [comment]
Hi, did you manage to solve the external mic problem(plug p3)?

**Comment by leocg** [comment]
> Hi, did you manage to solve the external mic problem(plug p3)?

I'm tried some solutions but didn't solve it yet. There's an app called ComboJack in order to make it work (https://github.com/lvs1974/ComboJack and https://github.com/hackintosh-stuff/ComboJack) but only work with other drivers. There's a way to add ALC236 to  hda-verb.m using instructions found at https://github.com/torvalds/linux/blob/master/sound/pci/hda/patch_realtek.c but I didn't mess with it yet
