### ISSUE TITLE
USB Fix

### ISSUE THREAD

**Issue by svinayak780** [leocg/Hackintosh-Dell-G5-5590#18]
Hi!
I have an [MSI GL63 9SDK](https://www.msi.com/Laptop/GL63-9SX-GTX/Specification). It has very similar hardware to G5 5590.
I am unable to get USB working on any version of macOS and hence can't get past the installer. I have followed the OpenCore Vanilla Guide.
The touchpad works but the physical keys don't work. Keyboard doesn't work either.

**Comment by leocg** [comment]
Hi! It really have very similar hardware, but the motherboard is from another vendor. It won't translate correctly all the patches I made for 5590, because each computer have different patches. CPU for example can be CPU0, PR00, CP00... Same will apply for PCI stuff and USB mapping. If you're really want to try this EFI, I would recommend removing USBMap.kext from config.plist and put USBInjectAll.kext to see if it will recognise the USB ports.

If USB ports work, you'll probably have to setup your audio codec (very unlikely it will share the same ALC236 codec). If CPU, GPU, iGPU mapping is correct and you can install and boot, you'll have to fix the network controller, bluetooth, wifi, etc

Apart from that, there's some configurations in the config.plist that's specifically for Dell Laptops, like CustomSMBIOSGuid and UpdateSMBIOSMode, you would probably need to change that too.

The headaches you'll get along the way to make it 100% compatible won't worth in my opinion, in case you can properly boot but don't get hardware acceleration and stuff like that. In that case I recommend follow the vanilla guide and make your custom EFI. Very similar laptops from same vendor have differences in BIOS and firmware, ex: my Dell G5 5590 have different patches and configurations from Dell G3 3390 and Dell G7 7790 that share same hardware. Even the Dell G5 line will have different configurations based on the version (with or without thunderbolt). When I started my research I tried the approach of using an existing EFI from a very similar laptop, but in the end I had to create my own. 

If you don't feel comfortable creating your own EFI, I suggest you to find the closest match from the same vendor (MSI), it may share the same ACPI naming.

**Comment by svinayak780** [comment]
I understand how the ACPI names might me completely different but I'm currently looking to just fix USB. I guess I can solve the rest on my own and I agree with you on the fact that it is never worth the pain to fix everything. Nonetheless I need USB to work in order to proceed with installation. I am a complete illiterate when it comes to DSDT stuff, so I am attaching my DSDT. See if you can help me figure out a way to fix USB.
PC: USB has Power.
[DSDT.zip](https://github.com/leocg/Hackintosh-Dell-G5-5590/files/7494448/DSDT.zip)

**Comment by leocg** [comment]
USB mapping don't need DSDT changes, you simply map USBPorts using USBMap (can do it from windows using [USBToolBox](https://github.com/USBToolBox), download tool and kext. Then you replace the new USBMap.kext with the old one on the EFI folder.

Another way to try is removing USBMap.kext from config.plist and adding USBInjectAll.kext. See https://dortania.github.io/OpenCore-Post-Install/usb/system-preparation.html

Keyboard and touchpad you'll have to discover witch driver to use, took me some time to make the trackpad working with multitouch.
For input devices I'm using VoodooI2C, VoodooI2CHID, VoodooInput and VoodooPS2Controller. You may need to use another solution depending on your hardware.
