### ISSUE TITLE
Annoying drag and Drop Issue!

### ISSUE THREAD

**Issue by al-jabirr** [leocg/Hackintosh-Dell-G5-5590#29]
https://drive.google.com/file/d/13mkK_ffTjZkcTX8uuqNICC4ZmwrewCYX/view?usp=sharing
This is an annoying problem. Please watch the entire video. This problem appears when the file is **_drag and drop anywhere_**.

**Comment by leocg** [comment]
Did you try another macOS on another SSD? Seems like something to do with your NVME hardware, I don't get any glitches with mine. Also, witch version of OpenCore are you using? Are you experiencing this problem with latest release (OpenCore 0.8.8)?


https://user-images.githubusercontent.com/3638669/215551707-b9da3bae-1115-449a-9da8-e3c931143ff1.mp4

**Comment by al-jabirr** [comment]
Assalamu Alaikum sir, first of all thank you for your quick response😍. **_It's finally fixed_**🥰. Today i formatted full ssd and reinstalled fresh in macOs Monterey. **Now I see that Glitch is gone.**

**Comment by al-jabirr** [comment]
**Again the problem started today**😭, you said to check on a new SSD but I don't have any other SSD to check for now😑

https://user-images.githubusercontent.com/8538407/216530474-21394471-6b9c-4c4b-8533-f73e15089b9c.mp4

, so now I'm going to do the big Sur test.😫

**Comment by leocg** [comment]
Hi, sorry to hear that!

From the 1st video I saw a lot of CPU usage during drag icons. Since you already make a new OS install, let's try some workarounds.

1. Review all BIOS configuration, make sure all itens are set equally. When I was building the EFI, sometimes one item change could leave weird behaviours.
2. Download latest EFI from release tab. Current version is Dell G5 5590 OpenCore 0.8.8 (v4.1)
3. Edit config.plist and put MacBookPro15,2 generated serials
4. If you undervolt, revert voltageshift to original voltage  ./voltageshift buildlaunchd 0 0 0
5. If you upgrade your BIOS to the newest version (DELL release a new BIOS firmware after you installed your hackintosh), you will need to disable CFGLock again. For testing purposes, you can try modifying this 2 entries from config.plist in order to run OpenCore with CFGLock enabled:

Kernel -> Quirks

AppleCpuPmCfgLock (change the value to 0 or NO, depending on the syntax of your editor. If it's 1 change to 0. If it's YES change to NO)
AppleXcpmCfgLock (change the value to 0 or NO, depending on the syntax of your editor. If it's 1 change to 0. If it's YES change to NO)

* You can use a pen drive to test new EFI. Just format pen drive as Mac OS Extended Journaled and GUID Partition Table. After format put clean EFI on the pen drive EFI folder. During boot press F12 to select it. If pen drive won't appear on F12 selection, enter BIOS and manually add entry, selecting **{USB_DRIVE}/EFI/OC/OpenCore.efi** OR **{USB_DRIVE}/EFI/BOOT/BOOTx64.efi**

Hope it helps!

**Comment by al-jabirr** [comment]
I have tried it, many times many ways but still can't solve it. Tried all the methods but the result is still the same. 😭😫😓

**Comment by al-jabirr** [comment]
I have tried it, many times many ways but still can't solve it. Tried all the methods but the result is still the same. 😭😫😓

**Comment by leocg** [comment]
Do you have a spare external USB3 drive? You can try installing macOS to the external disk and see if the issue persists. 

I recommend an USB3 drive because USB2 have slow transfer speed and could lead to the same issue when debugging.

**Comment by al-jabirr** [comment]
Assalamualaikum sir, I hope you are well. I finally managed to solve this problem🤩, I unchecked all the options for a thunderbolt from bios. I do not see this problem anymore and installed a new OS. Thank you very much❤️ for supporting us in this way.
