### ISSUE TITLE
it's working for  dell-G5-5500?

### ISSUE THREAD

**Issue by axkza** [leocg/Hackintosh-Dell-G5-5590#3]
it's working for  dell-G5-5500?

**Comment by leocg** [comment]
It may boot, but some stuff you'll have to figure out, like audio layout id.

Also you have to change in config.plist because your CFG Lock variable on bios may be different and I don't reccomend you disabling it with another model value:

AppleCpuPmCfgLock YES
AppleXcpmCfgLock YES

If your USB ports aren't working properly, you'll have to map USB ports by yourself. I used Hackintool map my ports.

You can read about post installation in https://dortania.github.io/OpenCore-Post-Install/

If you can't get into OS, you'll have to generate ACPI files correctly using https://dortania.github.io/OpenCore-Install-Guide/
