### ISSUE TITLE
* (Temperature) || karnel_task using High CPU  😐* 

### ISSUE THREAD

**Issue by al-jabirr** [leocg/Hackintosh-Dell-G5-5590#31]
Assalamu Alaikum Sir, I hope you are well🤗. I am here to _disturb you again 😅_ I found a new issue which was not there before. I didn't have this issue on my laptop when I first installed Hackintosh. I've seen in my activity monitor for a while now that the process called **_kernel_task is using High CPU_**, along with the fan rpm going up sometimes. So I started using it normally without thinking of it as a problem or any type of issue.

So yesterday all of my work finished **Suddenly I saw the temperature and fan rpm getting back to normal**😃, then I went to the activity monitor and saw that my **_kernel_task was using less CPU than before._**

**Then I restart the laptop after work, then again I see kernel_task is using a High CPU again 😔😩.**

I thought it was important to show you this, so I have included before and after videos and screenshots.
Please take some time out of your busy schedule to watch them. 🤗

## **High CPU use**: https://www.dropbox.com/scl/fo/9wqe7p200vnsbcy5onkv2/h?dl=0&rlkey=n8u54oyfxszr2mvmu8fc4g99n

![Screenshot 2023-02-16 at 6 06 26 PM](https://user-images.githubusercontent.com/8538407/219360553-0ca8f54c-7637-4d4a-becf-3882bb1d0eff.png)

**Comment by leocg** [comment]
Hi! Hope you are doing well!

Some Bios settings could lead to this issue. If I recall correctly, if you set Thunderbolt to Native instead of BIOS and some other Thunderbolt stuff. Setting thunderbolt exactly as described on the Readme.md will resolve the issue, but as you said before, the default configuration shown on Readme.md was leading your macOS to behave poorly with drag and drop. Try reverting the Thunderbolt settings to verify if the kernel_task issue is related to it.

best regards

**Comment by al-jabirr** [comment]
I hope you are well🤗, you are indeed right. You're right, the (kernel_task) was using a lot of High CPU due to completely disabling the thunderbolt option⚡. Now my machine Alhamdulillah is performing very well.🤩

NB: Sir, Can we connect on WhatsApp or another?
Please 🥺🫣

**Comment by leocg** [comment]
Glad you could resolve your issue!
