### ISSUE TITLE
Webcam detected but not working

### ISSUE THREAD

**Issue by HieuNVDSgit** [leocg/Hackintosh-Dell-G5-5590#37]
After install macOS Monterey on my Dell G5 (RTX 2060 rev) with your EFI Build and make it dual boot with Windows 11 22H2 I got problem with Webcam, both Windows and Mac are detected (in Windows Device Manager and Mac System Report) but:
- Windows Camera show no camera connected.
- Photobooth show blackscreen and camera light binking.
I try to change from OC 0.9.2 to OC 0.9.3 DEV no ACPI but no luck
- Windows Camera show blackscreen.
- Photobooth show blackscreen.
In Hackintool app, USB tab:
- Intergrade webcam show at HS05 port, as internal type but it's always blinking

What can I do to fix this?
Thanks!

![Screen Shot 2023-06-05 at 13 33 56](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/131596137/ba686409-438e-4931-a114-dd524b1ba85f)

**Comment by leocg** [comment]
Are you loading windows with OpenCore? I recommend load windows with BIOS selection, because ACPI changes may impact other OSs. I use OpenCore exclusively to load macOS and load Windows using BIOS, pressing F12 when Dell logo appears. You may have to manually add the correct boot entry at BIOS setup.

Your issue could be hardware related, since it happen with every OS and the webcam is automatically detected by macOS, didn't need any extra work with OpenCore to detect it.

My webcam is detected as Integrated_Webcam_HD and yours is detected as USB 2.0 Camera. Maybe your camera hardware is different somehow too.

![Screenshot 2023-06-05 at 09 46 47](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/3638669/e43573b5-f6e8-43d3-a6a3-59ebc7197220)

First try to load Windows using BIOS bootpicker and test webcam, then report back.

* Check if your Thunderbolt configuration match the Readme.md, Hackintool will detect it as JHL6340 Thunderbolt 3 USB 3.1 Controller (I don't think this will relate to webcam, but I'm trying to match your setup as close to mine as I can)

**Comment by HieuNVDSgit** [comment]
I think you're right. But on my laptop, MacOS and Windows dual boot on the same disk (follow Dortania Multiboot Guide) so only have one EFI partition. BIOS boot picker only have one option to boot from my SSD and it boot to Opencore Picker.
I tried to add another boot entry for Windows but i'm not found any Windows bootx64.efi, just have one bootx64.efi from Opencore package.
Your guide may be work correctly in case dual boot on 2 disk. One use Opencore bootx64.efi and one use bootx64.efi from Windows Installation.
PS1: I install Windows after instal MacOS and follow manual instal guide (use command line and extract install.wim package), not standard installation steps.
PS2: At the first time boot into MacOS (without Windows Installed) my webcam detected as Integrated_Webcam_HD but after install Windows, device name change to USB 2.0 Camera on both Windows and Mac.
PS3: Can you tell me something about what's new in next release?

Thanks in advanced for your support!

**Comment by leocg** [comment]
Look for \EFI\Microsoft\Boot\bootmgfw.efi to boot Windows. I don't know if your EFI partition will have this file, since you used another method to dual boot.

You can try a Live Linux USB stick like [Ubuntu](https://ubuntu.com/download/desktop). It won't load from your EFI partition, so you can test your webcam from there. I use [Etcher](https://etcher.io) to create a bootable USB.

The next release will be an update release (update OpenCore and kexts to new version). I don't think it will impact anything relevant in this machine. There's 2 issues I couldn't find a solution yet (external mic via headphone jack input and macOS freezing when remove and insert power cable a couple times) and it won't come in next release.
