### ISSUE TITLE
Display stuck at dimmest setting

### ISSUE THREAD

**Issue by TolleyLikesRice** [leocg/Hackintosh-Dell-G5-5590#38]
Hi, originally on 0.8.3, updated opencore myself, just seen this repo has been updated, just downloaded the ACPI and Drivers for 9.3 from here just incase, even though GitHub says they haven't changed. Just done an OTA update to Ventura from Big Sur, display goes dim at some point on the Apple logo loading screen. Dragging the slider once logged in doesn't do anything. Updated to 0.9.3 on Big Sur, all was well, only broken when going to Ventura. Any ideas on what to do?

**Comment by TolleyLikesRice** [comment]
Goddamn it, just fixed itself, no idea how, maybe it was those ACPIs but the slider works now. Sorry to bother.

**Comment by TolleyLikesRice** [comment]
Nevermind, not working again, just rebooted

**Comment by TolleyLikesRice** [comment]
And it's back? So, my exact process: I turn it on, it's very dim, slider does nothing, I open anydesk. Remote into anydesk from my machine. Somewhere between me anydesking and typing this, it works again, and slider is all good, and it's bright.

**Comment by nerijunior** [comment]
I'm facing the same issue but I'm not using the last update.

**Comment by leocg** [comment]
I had this issue in the past when I press enter at bootpicker just after it appear. Now I way a few seconds before pressing enter at opencore boot picker. Pressing enter just after bootpicker appear caused issues in other hardware, like audio, but they put an option at config.plist to have a delay in miliseconds (for audio issues only). Try waiting a few seconds before pressing enter at bootpicker. If you still have issues, please try OpenCore 0.9.0 release, because I changed graphics related settings after that in order to run a 4k display.

**Comment by HieuNVDSgit** [comment]
In my case, I have no issue with display dim. 
I'm running Ventura 13.4 with latest OC 0.9.3 (Monterey 12.6.6 with OC 0.9.2 before upgrade)
My display only dim in case I try to Reset NVRAM, after reboot, drag display brightness slider to max and it's alway bright in next boot

**Comment by leocg** [comment]
Yes, brightness status is stored in NVRAM. Same with volume status and other variables as seen running `nvram -p` from terminal

**Comment by leocg** [comment]
I didn't notice this issue because I was using dual external monitors with laptop lid closed. Today I had to use the laptop outside office and noticed it.

Fixed the issue with latest commit with @HieuNVDSgit suggestion and it's working fine.

Next release with OC 0.9.4 will come with this patch. For now just add `-igfxblt -igfxbls` to config.plist (NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args
