### ISSUE TITLE
Laptop screen stays off after boot

### ISSUE THREAD

**Issue by ernestojv** [leocg/Hackintosh-Dell-G5-5590#39]
Laptop screen stays off for several minutes after booting up, displays image on external monitors.
After 3 or 5 minutes, the screen turns on.

**Comment by HieuNVDSgit** [comment]
Edit your config.plist
Replace -igfxblr (if existing) in boot args with -igfxblt -igfxbls
Remove enable-backlight-registers-fix in NVram
Reboot

**Comment by nerijunior** [comment]
@leocg not about reopening the issue but how do you use two dual external? USB-C hub?

Could you share which USB-C hub are you using?

**Comment by leocg** [comment]
> @leocg not about reopening the issue but how do you use two dual external? USB-C hub?
> 
> Could you share which USB-C hub are you using?

I’m using Wavlink USB to HDMI adapter. Can deliver 1080p @ 60fps and 4k @ 30fps. Using it with second screen (1080p). Refresh rate is fine but sometimes I see more pixel on some areas like dock than I would like, but may be an illusion because main display is 4k (not sure if it’s a wavlink adapter issue)

bought this model on Amazon: WAVLINK Adaptador de Vídeo Universal USB 3.0 para Dual HDMI UHD - https://a.co/d/6j6n8M6
You can find at AliExpress to, but prices on Amazon was lower when I bought.

Main display is connected with USB-C to HDMI adapter and Wavlink is driving second display, plugged to USB3 port. After installing Wavlink driver, the connection is plug and play, no need to mess with OpenCore to work
