### ISSUE TITLE
Can you use brightness keys?

### ISSUE THREAD

**Issue by caiomascarin** [leocg/Hackintosh-Dell-G5-5590#4]
Hi! I have a Dell G5 5590 too, and using your OC config I cannot use brightness keys... So, I have a solution using SSDT-XOSI, SSDT-BRT6 and 3 renames in ACPI Patch. If you need some help, you can talk to me!

**Comment by leocg** [comment]
Hi, it would be nice! I didn't go deeper with brightness via ACPI because I'm using Karabiner to remap all function keys, but if karabiner don't load correctly on boot, pressing brightness keys crashes system. If you can send me some tips I could update the EFI folder. Did you update your BIOS to 1.14.0? I'm still on 1.13.2 looking for success cases before update. Thanks!

**Comment by caiomascarin** [comment]
Im using BIOS 1.12 👎 . To fix brightness keys I need to remove SSDT-GPIO, add SSDT-XOSI and add SSDT-BRT6. After, need to rename BRT6 to BRTX (using count=1 in OC ACPI Patch), OSID to XSID and _OSI to XOSI.

[brightness-fix.zip](https://github.com/leocg/Hackintosh-Dell-G5-5590/files/5640215/brightness-fix.zip)

**Comment by leocg** [comment]
Worked great, thanks!! I will update the repo on monday, waiting the release of OpenCore 0.6.4 with updated kexts.

Only annoying issue now is plugging in and out the power adapter more than once the system crashes. Do you have this issue also? I read some fixes in the past, but never got the spare time to get it done.

**Comment by caiomascarin** [comment]
Finee!! I havent tested the plug problem... I will test it tomorrow. My main problem now is the external microphone, because here I can only use internal mic 👎. Can you use combojack without problems?

**Comment by leocg** [comment]
I'm using a bluetooth headset but will test with a combojack one. Maybe we have to customize our ports, [I have this page bookmarked](https://github.com/F0x1c/AppleALC_Instructions) but never had the time to follow the guide.

**Comment by caiomascarin** [comment]
I've tested the plug power problem here and i've got the same problem as you. When I replug, the system freezes. Did you find anything about it?

**Comment by leocg** [comment]
I read a lot of topics covering this issue, but none of them worked. All topics I found was Clover related, none of them OpenCore. Some suggestions I followed already was change SMBIOS (tried MacBook Pro 15,1, MacBook Pro 16,1, none of them seems to resolve, so I reverted to MacBook Pro 15,2, the only one that works with external display using USB-C to HDMI adapter). Tried some ACPI patching, but no luck also. To be honest, I stopped searching for a solution for this because I have little free time to mess around. A workaround I'm using to avoid the freeze is closing the lid, waiting the computer enter sleep mode and plug/unplug in this state before reopen the lid.
