### ISSUE TITLE
could you help me?

### ISSUE THREAD

**Issue by hurricaneabel** [leocg/Hackintosh-Dell-G5-5590#44]
I know it's been a while since you made this diary, but I've been trying for almost a month to run the Hackintosh on the same machine but without success, either it hangs on startup, or it hangs on installation and restarts the machine, my bios is version 1.27. 0 and I can't downgrade it to this version, I saw some tutorials on the internet about cfg lock, I even checked that it is already disabled, but it still doesn't work, could you update the post or help me in some way to make the hackintosh work on my machine?

steps I'm following:

1 I downloaded and burned the vanilla image of sonoma, ventura, catalina by balena etcher, I placed its efi folder in the efi partition of the bootable pendrive.

2 I made all the settings in the bios that you told me to do, I enter opencore through f12 in the bios, I reset the nvram and start the installation

3 at this point it either freezes to create the partition in apfs or simply in the middle of the first part of the installation, the notebook simply freezes and restarts

4 the only time I managed to get past the first part, where the laptop restarted and went to that installation apple screen, it got stuck in 29 minutes and restarted several times but stuck in that part too.

So far that's all I've been able to do.

ps: I did that part of the smbios I also put everything correctly but it doesn't work, mine is a dell g5 15 5590, with i7 9750h and rtx 2060

**Comment by leocg** [comment]
Hi, I don't have the notebook anymore to update the guide with new bios version. Do you know the NVME SSD model? Some vendors aren't compatible with hackintosh, maybe that's the issue. See [this page](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html) with some storage devices that don't work

You can try to make some changes to config.plist in order to run without disabling CFG Lock, change 2 properties under Kernel->Quirks in order to boot macOS without disabling it:
AppleCpuPmCfgLock to YES or 1
AppleXcpmCfgLock to YES or 1

(if the app you're using to edit plist is showing NO, change to YES. If is showing 0, change to 1)

You can also try to install Ventura using [version 0.8.9](https://github.com/leocg/Hackintosh-Dell-G5-5590/releases/tag/v4.2-OC-0.8.9). Starting with 0.9.0 I need to make some hacks in order to run Sonoma with everything working, you can try to install Ventura with this EFI, changing the above settings to run without disabling CFG Lock.

If the steps above still hangs on install, the issue probably is the storage device. You can try the VERBOSE version of the EFI, to see what error is showing at the time the installation freeze, the verbose will show all logs on screen instead of the Apple logo.

**Comment by hurricaneabel** [comment]
Sorry for the delay, I had some health problems, in fact I managed to install it from your efi folder, even before your answer about the SSDs, I had another NVMe SSD here at home, and I put it to test and the first time I managed to install it Thank you very much, it's working fine in 1.27.0, I'm waiting for my wifi card to arrive to make the wifi work.
