### ISSUE TITLE
Thermal issues

### ISSUE THREAD

**Issue by ThePianoMan2255** [leocg/Hackintosh-Dell-G5-5590#6]
Running Catalina and found that the fan's don't ramp up to prevent over heating that I have heard. And Thermal throttling does not seem to be a thing. Anyone else find this?

**Comment by leocg** [comment]
Mine worked normally using SMCDellSensors in Catalina. I'm using Big Sur now, so I can't confirm if there's any change with kexts above OC version 0.6.2. What software are you using to monitor CPU temp and fans? This notebook keep fans at 0rpm if CPU temp is low (tested with windows, linux and macos). Running benchmark with geekbench will put the fans at 4k+rpm when the test goes beyond 1:30m

**Comment by ThePianoMan2255** [comment]
I am using both Intel power gadget and HWMonitor for for more accurate information. It doesn't appear that fans are an issue, after awhile they did kick up. its more of a throttle issue. Normally that comes down to SMBios which I started with MacBookPro16,1 and then went to 16,4. I am running on a 1660TI model if you would like more testers. Thank you for your quick response.

**Comment by ThePianoMan2255** [comment]
I am wondering, you are running on 15,2 which is a U series SMbios, the next H Series is 15,3 this could be why?

**Comment by leocg** [comment]
I'm running Handbrake to convert a video now, max frequency is throttled at 3.4ghz (core req is 4.5ghz). Click on Stop, core max went up to 4.2ghz soon after stopping, so it seems to be a cpu throttle here. I don't think it's a SMBios issue, because I'm running CPUFriend to boost CPU clock. Had to put 15,2 in order to use video out, but put a high performance profile with CPUFriendFriend. Try to convert a video and check intel power gadget to see if your frequency goes down to 3.x ghz

**Comment by ThePianoMan2255** [comment]
![Screen Shot 2021-02-11 at 10 26 21 AM](https://user-images.githubusercontent.com/61894631/107657974-addd9f00-6c53-11eb-8818-c206122cb9e7.png)
hmm, What is your idle temp? Maybe I have a thermal paste issue. it appears. I throttle but my temps just stay high.

**Comment by leocg** [comment]
My idle temp is between 42-49deg. This laptop runs hot, goes all the way to 99deg too fast. I have to put max cpu clock to 2.5ghz in windows in order to run games at 70deg. Any game without lowering the clock make the CPU run at 95-99 deg. If your idle temp is above 62 deg, maybe your dGPU isn't turning off correctly, but it doesn't seem to be the issue based on your graph.

I disable turbo boost (Turbo Boost Switcher) using CPU intensive tasks to prevent high temperatures (won't change thermal paste cause laptop still under warranty). Unfortunately this notebook get hot way to fast, I read a lot in the past about it. The answers were undervolt and using Thermal Grizzley Kryonaut to keep temps down.

If you boot in Windows and keep alienware command center open, you will see temps going up very quickly doing moderate tasks, like installing/uncompressing and stuff like that. Some people blame intel for chip design, other people blame dell for the thermal design of the laptop. Running a search for Dell G5 5590 temperature or Dell G5 5590 overheat will bring a lot of topics.

There's an interview with Dell's Thermal Engineering Technologist about this topic, he said it's ok to run at 99deg (https://www.youtube.com/watch?v=u2--SmLORIE +/- 10m30s min mark). I won't allow mine to run at this temp for too long, it could be ok for the CPU, but I think this temperature could fry other parts on the motherboard

**Comment by ThePianoMan2255** [comment]
Thanks for your thoughts, I like to keep mine below 80C, in windows Dell Power Manager with the cooling setting to cool even with turbo boost regulates everything under 80C even during Handbrake encodes.as far as the dgpu, that could be my issue, I do not have a windows install currently to find my bios name to attempt a Optimus disable. This and palm rejection are the largest pain for this Hackintosh build, ha, but Intel WiFi's work now so its not as big of a deal in that way. Do you have a messenger? maybe we can chat as far as finding fixes and issues? Thanks for all the work on the config

**Comment by leocg** [comment]
You can find me at Discord, SegrobOel#0801
