### ISSUE TITLE
Fan Control

### ISSUE THREAD

**Issue by giorgifernandes** [leocg/Hackintosh-Dell-G5-5590#7]
hello, first thanks for sharing your EFI, here everything is working almost 100%, I have a little problem with the fans, they are at 0% rpm, did you go through this?

already installed istat but it works intermittently.

**Comment by leocg** [comment]
Hi, this laptop keep fans at 0rpm when it's cool. I thought it was a issue too, but found out this behavior in Windows and Linux. Fans only kick in when CPU temp is at approx 60deg. Since dGPU is turned off, system tends to be cooler. 

If you run a benchmark test with geekbench, you'll see fans kicking in at 2400rpm all the way up to 4800rpm. When benchmark is over, it will keep at 2400rpm until cpu cool down and turn off when it's below 60deg. It's a strange behavior, all laptops I had before the fans was always running, even in idle. You can override the set with some tools like iStats ou Macs Fan Control, but both behave buggy with me and I kept the original system controlled state.

**Comment by giorgifernandes** [comment]
great, due to this possible problem i ended up leaving the installation and went back to ubuntu, i will install it again and try this test.

Attention with the opencore update: I tried to perform the opencore update (0.6.5 -> 0.6.6), this worked, but the WhateverGreen kext (required to update to a new version of opencore) when updated, generates a problem in brightness of the screen, that after a few minutes of the system working the brightness returns to work normally

Thanks for the feedback

**Comment by leocg** [comment]
Hi, just a heads up: I had some bluetooth issues and had to run a SMC reset. After resetting SMC, my fans started to kick in at lower temps. If you are experiencing fans at 0rpm when temps are above 49deg, you could try it too. 

To reset SMC, remove power cable with laptop off and press power button for 10 seconds. Hope it helps!
